name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to see?
      placeholder: Tell us what you expect!
    validations:
      required: false
  - type: input
    id: fastdup-version
    attributes:
      label: What version of fastdup were you runnning on?
      placeholder: ex. 0.918
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: What version of Python were you running on?
      multiple: true
      options:
        - Python 3.10
        - Python 3.9
        - Python 3.8
        - Python 3.7
        - Other
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System 
      description: What operating system and version were you runnning on?
      placeholder: ex. Ubuntu 22.04 LTS / macOS Ventura 13.3.1 (M1) / Windows 11
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error '...'
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: screenshot
    attributes:
      label: Attach a screenshot [Optional]
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details [Optional]
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false