name: Test Run Examples

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Trigger at 8 AM every day

jobs:
  test-quick-dataset-analysis:
    runs-on: ${{ matrix.os }}
    env:
        SENTRY_OPT_OUT: True
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            python-version: ['3.9']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastdup matplotlib==3.6.3

      - name: Download dataset
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            Invoke-WebRequest -Uri "https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz" -OutFile "images.tar.gz"
            Expand-Archive -Path "images.tar.gz" -DestinationPath "path/to/dataset"
          else
            wget "https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz" -O "images.tar.gz"
            tar xf "images.tar.gz" -C "path/to/dataset"
          fi

      - name: Run example
        run: |
          python .github/workflows/tests/quick_dataset_analysis.py
      
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fastdup_work_dir
          path: fastdup_work_dir/
