name: Test Run Examples

on: 
  push:

jobs:
  test-quick-dataset-analysis:
    runs-on: ubuntu-latest
    env:
        SENTRY_OPT_OUT: True
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastdup matplotlib

      - name: Download dataset
        run: |
          wget https://thor.robots.ox.ac.uk/~vgg/data/pets/images.tar.gz -O images.tar.gz
          tar xf images.tar.gz

      - name: Run example
        run: |
          python .github/workflows/tests/quick_dataset_analysis.py
      
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fastdup_work_dir
          path: fastdup_work_dir/
